### ISSUE TITLE
[Linux] Unable to get ./ipsw

### ISSUE THREAD

**Issue by citrusui** [parrotgeek1/ipod1ios4#2]
After executing [./run.sh](https://github.com/parrotgeek1/ipod1ios4/blob/master/run.sh), I get an error: "./ipsw: No such file or directory"

Here's a screenie of the events leading up to the error: 
![err](https://cloud.githubusercontent.com/assets/9056756/11766238/6ffa4c7e-a14c-11e5-9350-906442f0a169.png)

Note that this error occurs in the script [1getxpwn.sh](https://github.com/parrotgeek1/ipod1ios4/blob/master/scripts/1getxpwn.sh). From what I can tell, it looks like one of the dependencies for the ./ipsw script isn't correct.

I'm going to try and manually install any missing dependencies and report back my progress.

**Comment by citrusui** [comment]
Success! I got the dependency problem resolved. Just needed to install libbz2 and libpng via apt.

```bash
sudo apt-get install libbz2-dev libpng-dev
```

![success](https://cloud.githubusercontent.com/assets/9056756/11766282/4d339d4c-a14e-11e5-8a7a-ab216fc98966.png)

You should probably have these packages automatically install in the next update though.

**Comment by parrotgeek1** [comment]
I am just going to say "Install x/y/z if on Linux" and totally drop homebrew from the linux script.
